// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PluginList.Entity
{
    public partial class Plugin
    {
        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        public string pluginName { get; set; }
        [StringLength(500)]
        public string introduce { get; set; }
        [StringLength(500)]
        public string instruction { get; set; }
        [StringLength(500)]
        public string webUrl { get; set; }
        public int parTechnologyId { get; set; }
        public int userId { get; set; }
        public int status { get; set; }
    }
}